### ISSUE TITLE
Solicitud de Alta Establecimiento Deportivo

### ISSUE THREAD

**Issue by tomicatalini** [Joadevy/Donde-Jugamos#18]
Generar formulario para permitir la carga de los datos necesarios para realizar la solicitud de alta de un establecimiento deportivo.

**Campos:** 
- nombre 
- dirección (calle y número): dos campos distintos pero se deben juntar al enviar.
- ciudad (nombre y código postal): campos distintos y devolver en forma de Objeto City.
- teléfono 
- correo electrónico
- horario: seria el default y en mas de un campo.
- descripción: opcional pero recomendable.
- datos bancarios (CBU y/o Alias): campos distintos y son opcionales.
- tiempo de tolerancia para cancelar reservas: opcional.
- tiempo de tolerancia para el pago: opcional.

### Resumen

- [x] Generar Formulario.
- [x] Validación y envió de datos.
- [x] Inserción en db de Establecimiento Deportivo con estado **PENDIENTE**.
- [x] Agregar Ciudad en caso de no existir.
- [x] Verificar usuario logeado.
- [x] Aviso amigable de_SUCCESS_ o _ERROR_

_NOTAS_

_- EL acceso de debe poder realizar en todo momento para aquellos usuarios que no sean **propietario / admin**_ 
_- Para el caso de un **propietario** seria una opción dentro de la vista de sus establecimientos_ 
_- Podría enviar un email al **admin** a modo de aviso y que sea mas rápido_

**Comment by tomicatalini** [comment]
No existe el campo estado en SportCenter, deberíamos tenerlo para poder diferenciar si el esta inactivo por baja o inactivo a la espera de confirmación de la solicitud de alta.

**Comment by Joadevy** [comment]
> No existe el campo estado en SportCenter, deberíamos tenerlo para poder diferenciar si el esta inactivo por baja o inactivo a la espera de confirmación de la solicitud de alta.

Si queres agregarlo y armar una pr asi levanto el cambio en local, joya.

**Comment by tomicatalini** [comment]
Para tener en cuenta:

- No hay opción para la carga de deportes en el establecimiento (de momento)
- Un usuario puede tener únicamente un establecimiento..
- Al cargar un establecimiento y se le cambie el role al usuario, es necesario relogear para que tome ese cambio.

**Comment by Joadevy** [comment]
> Para tener en cuenta:
> 
> * No hay opción para la carga de deportes en el establecimiento (de momento)
> * Un usuario puede tener únicamente un establecimiento..
> * Al cargar un establecimiento y se le cambie el role al usuario, es necesario relogear para que tome ese cambio.

Buenisimo esto de marcar posibles consideraciones, y tengo algunas opiones/dudas de estas:
1. Las opciones de la carga de deportes donde decis vos que no esta? Yo creo que en el formulario de la solicitud inicial no deberia ser necesario en primera instancia, podriamos dejarselo en su dashboard una vez que tenga ese rol de propietario que se muestren las opciones para crear su cancha (ahi eligiria el deporte que le asocia a esa cancha), sus turnos y demas.

2. Lo del un usuario un establecimiento mepa que podriamos dejarlo asi para simplificar y fue pero entiendo que lo pusiste para que no nos olvidemos de eso

3. Interesante eso y tiene sentido porque se guarda un token jwt que tiene el rol del usuario que lo saca de la sesion del usuario por lo que va a tener que reloguear si para ver ese cambio, habria que notificarselo de alguna manera y fue, o sino hacer que cada que entras, tengas que iniciar sesion pero medio molesto seria eso

**Comment by tomicatalini** [comment]
> > Para tener en cuenta:
> > 
> > * No hay opción para la carga de deportes en el establecimiento (de momento)
> > * Un usuario puede tener únicamente un establecimiento..
> > * Al cargar un establecimiento y se le cambie el role al usuario, es necesario relogear para que tome ese cambio.
> 
> Buenisimo esto de marcar posibles consideraciones, y tengo algunas opiones/dudas de estas:
> 
> 1. Las opciones de la carga de deportes donde decis vos que no esta? Yo creo que en el formulario de la solicitud inicial no deberia ser necesario en primera instancia, podriamos dejarselo en su dashboard una vez que tenga ese rol de propietario que se muestren las opciones para crear su cancha (ahi eligiria el deporte que le asocia a esa cancha), sus turnos y demas.
> 2. Lo del un usuario un establecimiento mepa que podriamos dejarlo asi para simplificar y fue pero entiendo que lo pusiste para que no nos olvidemos de eso
> 3. Interesante eso y tiene sentido porque se guarda un token jwt que tiene el rol del usuario que lo saca de la sesion del usuario por lo que va a tener que reloguear si para ver ese cambio, habria que notificarselo de alguna manera y fue, o sino hacer que cada que entras, tengas que iniciar sesion pero medio molesto seria eso


Respondiendote a los consultas/dudas:

1. Digo que falta la carga de deportes en general. Entiendo que lo vamos a pre-cargar nosotros a eso pero por ahí no estaría mal que cuando se mande la solicitud de alta se incluya los deportes que va a tener el establecimiento, un campo de texto simple y que sea opcional de última. Mas que nada por si de repente aparece un deporte que no tuvimos en cuenta porque no creo que pongamos todos los deportes que existan como opción. Es un comentario para charlarlo no mas y/o dejarlo para futuro si hay tiempo.
2. Lo de que un usuario tenga un solo establecimiento en mi opinión me parece algo limitativo sin necesidad, vos decis que se complejice mucho el desarrollo por darle la opción a tener varios establecimientos? 
3. En mi caso, yo estaba planteando que al terminar de generar la solicitud que lo redirija al "dashboard" con el establecimiento en un estado _pendiente de confirmación_ y flashee que el usuario ya pasaba a ser propietario. Entonces al redirigirlo por ejemplo a la ruta */propietario/dashboard* el middleware me freno el carro y me mando al inicio, lo cual esta perfecto porque mas allá de que se cambio por base de datos el role, la sesión no conoce este cambio. 
De todos modos esta mal si porque el usuario pasaría a ser propietario cuando se el confirma la solicitud pero capaz sea molesto el hecho de tener que volver a loguear. Habría que ver si no existe la forma de poder modificarlo sin necesidad de reloguear.

**Comment by Joadevy** [comment]
1. Ah si podria ser de esa forma, esta bueno por ahi saberlo de antemano a los deportes para cubrirnos de la posibilidad de no tenerlo cargado por ejemplo, como un campo opcionalpodria ser. Lo unico de esto seria donde quedaria persistida esa data? Porque por ahora la "solicitud de alta del establecimiento" seria una fila de la tabla Sportcenter con el estado "pendiente", no? Donde podriamos poner esa info?

2. Nah, no creo que sea muy complejo, habria que cambiar esa relacion, y despues tenerlo en cuenta en el /propietario que vamos a traer un SportCenter[] y el tendria que seleccionar el que quisiera administrar en ese momento. Habria que ver si no rompe nada de lo que esta hecho eso si (creeria que no porque la mega query trae el usuario del sportcenter pero ese lado de la relacion no cambia, xq sigue siendo 1 el propietario de un establecimiento).

3. Sep, estaria buenisimo ver si se puede cambiar sin reloguear, imagino que tiene que estar la posibilidad. Habria que guardar esa anotacion para detalles finales que estarian piola.
