### ISSUE TITLE
Confirmación de Solicitud de Alta de Establecimiento Deportivo

### ISSUE THREAD

**Issue by tomicatalini** [Joadevy/Donde-Jugamos#19]
Generar la opción para la confirmación de solicitudes de alta de establecimientos deportivos **únicamente** para usuarios *ADMIN*.

### Requerimientos

- [x] Mostrar listados de solicitudes por pantalla.
- [x] Mostrar todos los datos del establecimiento al hacer click en otra pantalla o en la misma pantalla.
- [x] Habilitar botones para _aceptar_ o _rechazar_ la solicitud
- [x] _(Opcional)_ En caso de que se haya rechazado la solicitud permitir el ingreso del motivo de rechazo.
- [ ] _(Opcional)_ Enviar email informando al propietario.
- [x] Modificar el *estado* de establecimiento en db.

_NOTAS_

- Al envió de emails lo puse como opcional porque no se si es parte de este requerimiento o va a ser un requerimiento a parte.

**Comment by Joadevy** [comment]
Por las dudas voy a estar implementando lo del envio de emails con nodemailer (y un gmail inventado para este proyecto) que lo tengo visto de como se hace, y la idea seria llamar a esa funcion cada que necesitemos un envio de mail, le pasamos a quien se lo mandamos, asunto y htmlBody con el contenido del mail

**Comment by tomicatalini** [comment]
> Por las dudas voy a estar implementando lo del envio de emails con nodemailer (y un gmail inventado para este proyecto) que lo tengo visto de como se hace, y la idea seria llamar a esa funcion cada que necesitemos un envio de mail, le pasamos a quien se lo mandamos, asunto y htmlBody con el contenido del mail

Okas

**Comment by Joadevy** [comment]
> Por las dudas voy a estar implementando lo del envio de emails con nodemailer (y un gmail inventado para este proyecto) que lo tengo visto de como se hace, y la idea seria llamar a esa funcion cada que necesitemos un envio de mail, le pasamos a quien se lo mandamos, asunto y htmlBody con el contenido del mail

Implementado, la funcion es handleSendEmail(emailTo, subject, htmlBody) en src/backend/email/nodemailer.ts. Se le pasan los parametros y se conecta con las credenciales del email creado y envia el correo. El htmlBody que recibe por parametro puede ser cualquier codigo HTML y se muestra en el cuerpo del mail. 

Ademas, se armaron templates (en /backend/email/templates) que dentro de cada tienen una export funcion  compileTemplate() que recibe ciertos parametros y devuelve un HTML Custom que seria lo que se le pasa en el htmlBody (todo esto para que quede mas "lindo" el cuerpo del mail)
