### ISSUE TITLE
Generación de Turnos

### ISSUE THREAD

**Issue by tomicatalini** [Joadevy/Donde-Jugamos#28]
La idea es mantener lo mas simple posible la generación de turnos como hablamos con la profe.

Generar una opción para el usuario *propietario* que permita definir dentro de un rango de fechas los turnos para una cancha en particular. Este rango de fechas debe tener un límite superior de *dos semanas* o *un mes*.
Para lograr esto se debe:

1. Desvincular *DiaTrabajo* con Turno, ya que no aporta nada esa relación.
2. Vincular *DiaTrabajo* con Cancha en lugar del Establecimiento. Esto nos permite mas flexibilidad a la hora de asignar casos especiales a una cancha en especifico.
3. Generar los horarios de apertura y cierre de una cancha para cada día. _Tabla DiaTrabajo, al momento de dar de alta canchas_
4. Para el calculo de turnos se va a tener:

- Rango de fechas. _ingresados por el usuario_
- Por cada fecha buscar horario de apertura y cierre de la cancha. _DiaTrabajo_
- Duración del turno de la disciplina asociada a la cancha. _Disciplina_

Con estos datos ya se podrían generar los turnos para una cancha.

_OPCIONAL: darle la opción al usuario de seleccionar una o mas canchas y aplicar la configuración que se esta realizando para todas y no tener que hacer una a una._

### Visualización

Se hablo la idea de hacer una especie de _Simulación_ de la generación de los turnos para que el usuario puede hacer modificaciones antes de generar los turnos realmente. Por ejemplo, mostrarle por pantalla como quedaría la generación de turnos y que el vaya anulando a su antojo.

La otra opción es generarlos y que el usuario vaya a cada cancha y modifique desde la pantalla de "cancha".

### Posibles Mejoras a Futuro

- Corrección en los limites para el rango de fechas ingresados por el usuario.
- Buscar una vuelta de turca a la generación de turnos para fechas especiales como feriados o días que se comporten distintos. Un buen consejo de la profe fue informarle al usuario que tal día es feriado por ejemplo.

**Comment by Joadevy** [comment]
Por las dudas, voy a meter las modificaciones 1 y 2 en la db con el agregado del campo nombre y 1 usuario * establecimientos en la proxima PR (Entre hoy - maniana).

**Comment by tomicatalini** [comment]
Joya, yo estoy con esta issue
